apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student9
  name: student9-deployment
spec:
  selector:
    matchLabels:
      app: student9
  template:
    metadata:
      labels:
        app: student9
    spec:
      containers:
      - name: student9
        image: registry.tanzu.dk/ops2devops/student9:v1
