apiVersion: apps/v1
kind: Deployment
metadata:
  name: student9-deployment
  namespace: student9
spec:
  selector:
    matchLabels:
      app: student9
  template:
    metadata:
      labels:
        app: student9
    spec:
      containers:
      - name: student9
        image: registry.tanzu.dk/ops2devops/student9:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student9
spec:
  type: NodePort
  selector:
    app: student9
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30019 # Remember to change to student number.

